name: Build and Deploy via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.shrisakthi.in
          username: github@shrisakthi.in
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./emi # Change this to your target directory on the server
          protocol: ftp
          port: 21
